services:
     db_test:
       image: postgres:17-alpine
       container_name: loom_postgres_test
       environment:
         POSTGRES_USER: loom_test
         POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
         POSTGRES_DB: loom_test_db
       ports:
         - "127.0.0.1:5433:5432"
       volumes:
         - postgres_test_data:/var/lib/postgresql/data

volumes:
     postgres_test_data: